### ISSUE TITLE
好久开源呀？

### ISSUE THREAD

**Issue by xiyangyang99** [yxchng/mask-grounding#1]
对作者的CAM模块很感兴趣。好久开源呀？

**Comment by yxchng** [comment]
@xiyangyang99 CVPR前开源，在准备中

**Comment by xiyangyang99** [comment]
> @xiyangyang99 CVPR前开源，在准备中

6.17号之前吗？大佬

**Comment by xiyangyang99** [comment]
> > @xiyangyang99 CVPR前开源，在准备中
> 
> 6.17号之前吗？大佬

![540ccab1d04f2d73444924011c8d3c94](https://github.com/yxchng/mask-grounding/assets/32487883/77416c02-9e67-40ad-9153-eaa8c6b5f03b)
大佬再不开源我都要把CAM模块复现出来用在其他网络里面了哟！比心

**Comment by xxxxyliu** [comment]
> > > @xiyangyang99 CVPR前开源，在准备中
> > 
> > 
> > 6.17号之前吗？大佬
> 
> ![540ccab1d04f2d73444924011c8d3c94](https://private-user-images.githubusercontent.com/32487883/338791377-77416c02-9e67-40ad-9153-eaa8c6b5f03b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODU3MjEsIm5iZiI6MTcyNTU4NTQyMSwicGF0aCI6Ii8zMjQ4Nzg4My8zMzg3OTEzNzctNzc0MTZjMDItOWU2Ny00MGFkLTkxNTMtZWFhOGM2YjVmMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDZlNzNkYzZhNzE1ZTAxMTYyNTA2MTM1NTExMTMxYTljODhiYjY5ZGU3YzIwZDU4YmE3MTk2OTU4ODZkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v-RPfGyBca5Q-xgX5mV_RNU5M6AiKCY8eODeVVQmanY) 大佬再不开源我都要把CAM模块复现出来用在其他网络里面了哟！比心

大佬复现的 CAM 模块可以给参考参考不～

**Comment by yxchng** [comment]
@xxxxyliu CAM 在这里 https://github.com/yxchng/mask-grounding/blob/2debc7ed18ed5b77f9863340f014895b5d8186ab/lib/backbone.py#L521-L779

**Comment by xxxxyliu** [comment]
> @xxxxyliu CAM 在这里
> 
> https://github.com/yxchng/mask-grounding/blob/2debc7ed18ed5b77f9863340f014895b5d8186ab/lib/backbone.py#L521-L779

感谢回复～不过，这部分不是只做了语言和图像的融合对视觉部分的处理吗？也并没有返回语言的特征。

**Comment by yxchng** [comment]
@xxxxyliu https://github.com/yxchng/mask-grounding/blob/2debc7ed18ed5b77f9863340f014895b5d8186ab/bert/multimodal_bert.py#L100 语言的在这，对称的

**Comment by xxxxyliu** [comment]
> @xxxxyliu
> 
> https://github.com/yxchng/mask-grounding/blob/2debc7ed18ed5b77f9863340f014895b5d8186ab/bert/multimodal_bert.py#L100
> 
> 语言的在这，对称的

好滴~感谢回复！
