### ISSUE TITLE
我想请教一个关于你的开源代码的问题呢~

### ISSUE THREAD

**Issue by RobinLiuZX** [yxchng/mask-grounding#5]
请问你的这个项目只是提供了关于模型的验证部分的代码吗？有没有提供训练部分的代码呢？还有我似乎没有找到你的代码中关于掩码具体目标的类别的词对应token的部分，请问你实现的过程中是怎么将具体目标的类别的词对应token进行掩码的呢？

**Comment by yxchng** [comment]
refer to the code here, https://github.com/alirezazareian/ovr-cnn/blob/c904af7455658906abaeaa1ff6c4cbe182efa08d/maskrcnn_benchmark/modeling/language_backbone/word_embedding.py#L76-L98
